interne_seance_tag:
    resource: "@InterneSeanceBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

interne_seance:
    path: /
    defaults: { _controller: InterneSeanceBundle:Default:index }

interne_seance_demo:
    path: /demo
    defaults: { _controller: InterneSeanceBundle:Default:demo }

interne_seance_demo_seance:
    path: /demo_seance
    defaults: { _controller: InterneSeanceBundle:Default:seance }

interne_seance_frontend:
    resource: "@InterneSeanceBundle/Resources/config/routing/frontend.yml"
    prefix: /frontend
    options:
        expose: true

interne_seance_export:
    path: /pdf/{id}
    defaults: { _controller: InterneSeanceBundle:Export:exportToPDF}
    options:
        expose: true