interne_seance_meeting:
    type: rest
    resource: "@InterneSeanceBundle/Resources/config/routing/meeting.yml"
    prefix: /meeting

interne_seance_item:
    type: rest
    resource: "@InterneSeanceBundle/Resources/config/routing/item.yml"
    prefix: /item

interne_seance_container:
    type: rest
    resource: "@InterneSeanceBundle/Resources/config/routing/container.yml"
    prefix: /container