services:
#    interne_seance.example:
#        class: Interne\SeanceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    interne_seance.type.entity_hidden:
       class: Interne\SeanceBundle\Form\EntityHiddenType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
       - { name: form.type, alias: entity_hidden }

    interne_seance.decoder.json:
        class: Interne\SeanceBundle\Decoder\JsonDecoder
        arguments: []