<?php

namespace Interne\SeanceBundle\Entity;

/**
 * ContainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContainerRepository extends \Doctrine\ORM\EntityRepository
{
}
