get_items:
    type: rest
    path: /all/{id}
    defaults: {_controller: InterneSeanceBundle:Item:getItems }
    methods: [GET]
    requirements:
        id: \d+

get_item:
    type: rest
    path: /{id}
    defaults: {_controller: InterneSeanceBundle:Item:getItem }
    methods: [GET]

new_item:
    type: rest
    path: /new
    defaults: {_controller: InterneSeanceBundle:Item:newItem }
    methods: [POST]

edit_item:
    type: rest
    path: /{id}/edit
    defaults: {_controller: InterneSeanceBundle:Item:editItem }
    methods: [PUT]

delete_item:
    type: rest
    path: /{id}/delete
    defaults: {_controller: InterneSeanceBundle:Item:deleteItem }
    methods: [DELETE]