get_meetings:
    type: rest
    path: /all
    requirements:
        _method: GET

get_meeting:
    type: rest
    path: /{id}
    requirements:
        _method: GET

new_meeting:
    type: rest
    path: /new
    requirements:
        _method: POST

edit_meeting:
    type: rest
    path: /{id}/edit
    requirements:
        id: \d+
        _method: PUT

delete_meeting:
    type: rest
    path: /{id}
    requirements:
        _method: DELETE