get_meetings:
    type: rest
    path: /all
    defaults: { _controller: InterneSeanceBundle:Meeting:getMeetings }
    methods: [GET]

get_meeting:
    type: rest
    path: /{id}
    defaults: {_controller: InterneSeanceBundle:Meeting:getMeeting }
    methods: [GET]

new_meeting:
    type: rest
    path: /new
    defaults: {_controller: InterneSeanceBundle:Meeting:newMeeting, _format: ~ }
    methods: [POST]

edit_meeting:
    type: rest
    path: /{id}/edit
    defaults: {_controller: InterneSeanceBundle:Meeting:editMeeting }
    methods: [PUT]

delete_meeting:
    type: rest
    path: /{id}
    defaults: {_controller: InterneSeanceBundle:Meeting:deleteMeeting }
    methods: [DELETE]