tag:
    path:     /
    defaults: { _controller: "InterneSeanceBundle:Tag:index" }

_ajax_edit_tag:
    pattern:    /ajax_edit_get_form_modal
    defaults:   { _controller: "InterneSeanceBundle:Tag:ajaxGetTag" }
    methods:    POST
    options:
        expose: true

_ajax_join_tag:
    pattern:    /ajax_jointag_get_form_modal
    defaults:   { _controller: "InterneSeanceBundle:Tag:ajaxJoinTag" }
    methods:    POST
    options:
        expose: true

# Traitement des données
tag_create:
    path:     /create
    defaults: { _controller: "InterneSeanceBundle:Tag:create" }
    methods:  POST

tag_update:
    path:     /{tag}/update
    defaults: { _controller: "InterneSeanceBundle:Tag:update" }
    methods:  [POST, PUT]

tag_delete:
    path:     /{tag}/delete
    defaults: { _controller: "InterneSeanceBundle:Tag:delete" }
    methods:  [POST, DELETE]

tag_join:
    path:   /{}
